name: Deploy to Firebase Hosting on PR
'on': pull_request
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Check lint
        run: yarn check:lint

      - name: Check prettier
        run: yarn check:prettier

      - name: Build
        run: yarn build


      - name: Deploy Preview to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PABLOPISKUNOW }}'
          projectId: pablopiskunow
          expires: 7d
